### ISSUE TITLE
libwayland-server 1.18 100% CPU usage

### ISSUE THREAD

**Issue by myfreeweb** [jiixyj/epoll-shim#15]
With [wayland 1.18](https://reviews.freebsd.org/D23643) there's a new [event loop update](https://gitlab.freedesktop.org/wayland/wayland/commit/60a8d29ad852) that would've fixed the same issue as #8 :D but now there's 100% CPU consumption in wlroots based compositors at least. [Here's a dtrace flamegraph](https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/wayland-g60a8d29-wf.svg), lots of time spent in `poll`, `kevent` and `ktimer_settime`…

**Comment by jiixyj** [comment]
Hm, maybe one of `set_timer`/`clear_timer` [here](https://gitlab.freedesktop.org/wayland/wayland/commit/60a8d29ad852#c7d68d6731e514eb6af9801fe396dbe9a60a3a35_221_260) is not correctly implemented yet in the shim... Maybe `clear_timer` doesn't actually clear the timer, making the event loop spin. I'll try to write a small reproducer.

**Comment by jiixyj** [comment]
Found the issue: the new Wayland event loop does not `read(2)` from the timerfd at all. This is OK if clearing the timerfd with `timerfd_settime` because all pending events will be deleted. The current implementation in epoll-shim doesn't do this correctly when using the old POSIX per process timer backend. This backend is still used for `TFD_TIMER_ABSTIME` timerfds.

In the Wayland case we could make it use the faster kqueue/EVFILT_TIMER backend anyway as they always set `it_interval` of the `struct itimerspec` to 0. We could also think about using `NOTE_ABSTIME`.

**Comment by zeising** [comment]
Is this a change you want in wayland or in libepoll-shim?

**Comment by myfreeweb** [comment]
@zeising "The current implementation in epoll-shim doesn't do this correctly" should imply that a fix is required here in epoll-shim :)

**Comment by zeising** [comment]
@myfreeweb Yeah, I just missed that on the first read-through. Sorry. :(

**Comment by shamazmazum** [comment]
I've also reported this. Maybe in the wrong repo, though

https://github.com/FreeBSDDesktop/epoll-shim/issues/6

**Comment by jiixyj** [comment]
Please try PR #16 ! I've thrown out the old POSIX per process timer backend. Now, kqueue EVFILT_TIMER is used exclusively. So no more limit of 32 timerfd's when using `TFD_TIMER_ABSTIME`.

**Comment by jbeich** [comment]
#16 works fine for me: CPU usage is normal after removing [workaround](https://github.com/freebsd/freebsd-ports/blob/c198bf5de20a6/graphics/wayland/files/patch-src_event-loop.c). Tested on Sway + Xwayland and xf86-input-libinput on FreeBSD 13.0-CURRENT.

**Comment by myfreeweb** [comment]
Yep, works great for me as well so far! Nice!

**Comment by jiixyj** [comment]
This should hopefully be fixed by PR #16, please let me know if I missed something!
